version: '3.8'

networks:
  net-docker:
    external: false

services:
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper
    networks:
    # restart: always
    networks:
      - net-docker
    ports:
      - 2181:2181
    volumes:
      - ./conf:/conf
      - ./data:/data
      - /data/log/zookeeper:/datalog

