version: '3.8'

networks:
  net-docker:
    external: true

services:
  mysql:
    image: mysql:5.7-oracle
    container_name: mysql_master
    networks:
      - net-docker
    mem_limit: 512m
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306" # mysql -h 127.0.0.1 -P 3307 -u root -p'123'
    volumes:
      - ./mysql_master.cnf:/etc/my.cnf
      - /data/mysql_data:/var/lib/mysql

  mysql2:
    image: mysql:5.7-oracle
    container_name: mysql_slave
    depends_on:
      - mysql
    networks:
      - net-docker
    mem_limit: 512m
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 456
    ports:
      - "3308:3306" # mysql -h 127.0.0.1 -P 3308 -u root -p'123'
    volumes:
      - ./mysql_slave.cnf:/etc/my.cnf
      - /data/mysql_data2:/var/lib/mysql

