version: '3.8'

networks:
  net-docker:
    external: false

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    networks:
      - net-docker
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: '/'
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
